/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.davidg95.JTill.jtillserver;

import io.github.davidg95.JTill.jtill.*;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class BarcodeSettings extends javax.swing.JInternalFrame {

    private static BarcodeSettings window;

    private final DataConnect dc;

    /**
     * Creates new form PluSettings
     */
    public BarcodeSettings() {
        this.dc = GUI.gui.dc;
        initComponents();
        super.setClosable(true);
        super.setIconifiable(true);
        super.setFrameIcon(new ImageIcon(GUI.icon));
        setTitle("Barcode Settings");
        init();
    }

    public static void showWindow() {
        if (window == null || window.isClosed()) {
            window = new BarcodeSettings();
            GUI.gui.internal.add(window);
        }
        window.setVisible(true);
        try {
            window.setIcon(false);
            window.setSelected(true);
            window.init();
        } catch (PropertyVetoException ex) {
            GUI.LOG.log(Level.SEVERE, null, ex);
        }
    }

    private void init() {
        try {
            String upc = dc.getSetting("UPC_PREFIX");
            int length = Integer.parseInt(dc.getSetting("BARCODE_LENGTH"));
            String next = dc.getSetting("NEXT_PLU");
            txtUPC.setText(upc);
            cmbLength.setSelectedItem(Integer.toString(length));

            int lengthToAdd = length - upc.length() - 1; //Work out how many more digits need added
            lengthToAdd -= next.length(); //Subtract the length to find out how many digits need added
            for (int i = 1; i <= lengthToAdd; i++) {
                next = 0 + next; //Pad it out with zero's to make up the length
            }
            String barcode = upc + next; //Join them all together
            int checkDigit = Utilities.calculateCheckDigit(barcode);
            barcode = barcode + checkDigit;
            txtNext.setText(barcode);
            int max = (int) Math.pow(10, length - upc.length() - 1);
            int remaining = max - Integer.parseInt(next);
            lblMax.setText("Max Barcodes: " + max);
            lblRemaining.setText("Remaining Barcodes: " + remaining);
            if (remaining == 0) {
                JOptionPane.showMessageDialog(this, "There are no more avaliable barcodes for this UPC Prefix", "No More Barcodes", JOptionPane.WARNING_MESSAGE);
            }
        } catch (IOException ex) {
            GUI.LOG.log(Level.SEVERE, null, ex);
        }
    }

    private void saveUPC() {
        String upc = txtUPC.getText();

        if (upc.equals("")) {
            JOptionPane.showMessageDialog(this, "If you do not specify a prefix, you will not be able to generate any barcodes", "UPC Prefix", JOptionPane.WARNING_MESSAGE);
        } else if (upc.length() < 6 || upc.length() > 10) {
            JOptionPane.showMessageDialog(this, "UPC Prefix must be between 6 and 10 characters long", "UPC Prefix", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (!upc.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Must only contain numbers", "UPC Prefix", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            dc.setSetting("UPC_PREFIX", upc);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex, "UPC Prefix", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void saveLength() {
        int l = Integer.parseInt((String) cmbLength.getSelectedItem());
        String length = Integer.toString(l);

        try {
            dc.setSetting("BARCODE_LENGTH", length);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex, "Barcode Length", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUPC = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNext = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        cmbLength = new javax.swing.JComboBox<>();
        lblMax = new javax.swing.JLabel();
        lblRemaining = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jLabel1.setText("UPC Company Prefix:");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel2.setText("Length for generating barcodes:");

        jLabel3.setText("Next barcode:");

        txtNext.setEditable(false);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        cmbLength.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "12", "13", "14" }));

        lblMax.setText("Max Barcodes: 0");

        lblRemaining.setText("Remaining Barcodes: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblMax)
                        .addGap(18, 18, 18)
                        .addComponent(lblRemaining)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUPC)
                            .addComponent(txtNext, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(cmbLength, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtUPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(lblMax)
                    .addComponent(lblRemaining))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int prefixLength = txtUPC.getText().length();

        int barcodeLength = Integer.parseInt((String) cmbLength.getSelectedItem());

        if (prefixLength < 6 || prefixLength > 10) {
            JOptionPane.showMessageDialog(this, "UPC Prefix must be between 6 and 10 characters long", "Plu settings", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (barcodeLength <= prefixLength) {
            JOptionPane.showMessageDialog(this, "Your barcode length must be greater than your UPC Prefix length", "Plu settings", JOptionPane.ERROR_MESSAGE);
            return;
        }
        saveUPC();
        saveLength();
        JOptionPane.showMessageDialog(this, "Settings saved", "Plu Settings", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        try {
            dc.setSetting("NEXT_PLU", "0");
            init();
        } catch (IOException ex) {
            GUI.LOG.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnResetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbLength;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblRemaining;
    private javax.swing.JTextField txtNext;
    private javax.swing.JTextField txtUPC;
    // End of variables declaration//GEN-END:variables
}
