/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.davidg95.JTill.jtillserver;

import io.github.davidg95.JTill.jtill.Category;
import io.github.davidg95.JTill.jtill.DataConnect;
import io.github.davidg95.JTill.jtill.Department;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author David
 */
public class BrowserWindow extends javax.swing.JFrame {

    private final DataConnect dc;

    /**
     * Creates new form BrowserWindow
     */
    public BrowserWindow() {
        this.dc = GUI.gui.dc;
        initComponents();
        try {
            init();
        } catch (IOException | SQLException ex) {
            Logger.getLogger(BrowserWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void init() throws IOException, SQLException {
        DefaultMutableTreeNode top = new DefaultMutableTreeNode("Products");
        createNodes(top);
        DefaultTreeModel model = new DefaultTreeModel(top);
        tree.setModel(model);
    }

    private void createNodes(DefaultMutableTreeNode root) throws IOException, SQLException {
        List<Department> departments = dc.getAllDepartments();
        for (Department d : departments) {
            DefaultMutableTreeNode dep = new DefaultMutableTreeNode(d.getName());
            List<Category> categorys = dc.getCategoriesInDepartment(d.getId());
            for (Category c : categorys) {
                DefaultMutableTreeNode cat = new DefaultMutableTreeNode(c.getName());
                dep.add(cat);
            }
            root.add(dep);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(tree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables
}
