/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.davidg95.JTill.jtillserver;

import io.github.davidg95.JTill.jtill.*;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Dialog which shows all current connected clients.
 *
 * @author David
 */
public class ConnectionsDialog extends javax.swing.JInternalFrame {

    private static ConnectionsDialog dialog;

    private final DataConnect dc;
    private MyListModel model;

    /**
     * Creates new form ConnectionsDialog
     *
     * @param dc the data connection.
     */
    public ConnectionsDialog(DataConnect dc) {
        super();
        this.dc = dc;
        initComponents();
        super.setClosable(true);
        super.setIconifiable(true);
        super.setFrameIcon(new ImageIcon(GUI.icon));
        setList();
    }

    /**
     * Method to show the connections dialog.
     *
     * @param dc the data connection.
     */
    public static void showConnectionsDialog(DataConnect dc) {
        if (dialog == null) {
            dialog = new ConnectionsDialog(dc);
            GUI.gui.internal.add(dialog);
        }
        dialog.setVisible(true);
        try {
            dialog.setSelected(true);
            dialog.setIcon(false);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ConnectionsDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private class MyListModel extends AbstractListModel {

        private final List<Till> tills;

        public MyListModel(List<Till> tills) {
            this.tills = tills;
        }

        @Override
        public int getSize() {
            return tills.size();
        }

        @Override
        public Till getElementAt(int index) {
            return tills.get(index);
        }

    }

    /**
     * Method to display the contents of the list in the dialog.
     */
    private void setList() {
        try {
            List<Till> tills = dc.getAllTills();
            for (Till t : dc.getConnectedTills()) {
                for (Till ti : tills) {
                    if (ti.equals(t)) {
                        ti.setConnected(true);
                    }
                }
            }
            model = new MyListModel(tills);
            lstConnections.setModel(model);
        } catch (IOException | SQLException ex) {
            Logger.getLogger(ConnectionsDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstConnections = new javax.swing.JList<>();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Connections");
        setResizable(false);

        lstConnections.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstConnections.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstConnectionsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstConnections);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void lstConnectionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstConnectionsMouseClicked
        if (evt.getClickCount() == 2) {
            try {
                Till t = dc.getAllTills().get(lstConnections.getSelectedIndex());
                try {
                    List<Sale> sales = dc.getUncachedTillSales(t.getId());
                    BigDecimal unCashed = BigDecimal.ZERO;
                    for (Sale s : sales) {
                        unCashed = unCashed.add(s.getTotal());
                    }
                    t.setUncashedTakings(unCashed);
                } catch (JTillException ex) {
                    Logger.getLogger(ConnectionsDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
                TillDialog.showDialog(this, t);
                dc.updateTill(t);
            } catch (IOException | SQLException | JTillException ex) {
                JOptionPane.showMessageDialog(this, ex, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_lstConnectionsMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstConnections;
    // End of variables declaration//GEN-END:variables
}
