/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.davidg95.JTill.jtillserver;

import io.github.davidg95.JTill.jtill.DataConnect;
import io.github.davidg95.JTill.jtill.JTillException;
import io.github.davidg95.JTill.jtill.Plu;
import io.github.davidg95.JTill.jtill.Product;
import io.github.davidg95.JTill.jtill.Sale;
import io.github.davidg95.JTill.jtill.SaleItem;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David
 */
public class ManualSaleWindow extends javax.swing.JInternalFrame {

    private final DataConnect dc;

    private Sale sale;

    private final DefaultTableModel model;

    /**
     * Creates new form ManualSaleDialog
     */
    public ManualSaleWindow() {
        dc = GUI.gui.dc;
        initComponents();
        setTitle("Manual Sale");
        super.setClosable(true);
        super.setMaximizable(true);
        super.setIconifiable(true);
        model = (DefaultTableModel) table.getModel();
        init();
    }

    public static void showWindow() {
        ManualSaleWindow window = new ManualSaleWindow();
        GUI.gui.internal.add(window);
        window.setVisible(true);
        JOptionPane.showMessageDialog(window, "This is a beta feature", "BETA Feature!", JOptionPane.WARNING_MESSAGE);
    }

    private void init() {
        sale = new Sale(-1, GUI.staff.getId());
        model.setRowCount(0);
    }

    private void addItem(Product p, int q) {
        sale.addItem(p, q);
        refreshTable();
    }

    private void refreshTable() {
        model.setRowCount(0);
        BigDecimal total = BigDecimal.ZERO;
        for (SaleItem si : sale.getSaleItems()) {
            try {
                final Product p = (Product) si.getItem();
                final Plu pl = dc.getPluByProduct(p.getId());
                Object[] s = new Object[]{pl.getCode(), p.getLongName(), si.getQuantity(), si.getTotalPrice()};
                total = total.add(si.getPrice().multiply(new BigDecimal(si.getQuantity())));
                model.addRow(s);
            } catch (IOException | JTillException ex) {
                Logger.getLogger(ManualSaleWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        lblTotal.setText("Total: £" + total.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnComplete = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Barcode", "Name", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
        }

        btnAdd.setText("Add Item");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnComplete.setText("Complete Sale");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        lblTotal.setText("Total: £0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnComplete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdd)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotal)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnComplete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        final Product p = ProductSelectDialog.showDialog(this, true);
        if (p == null) {
            return;
        }
        if (p.isOpen()) {
            double price = Double.parseDouble(JOptionPane.showInternalInputDialog(GUI.gui.internal, "Enter price", "Sale", JOptionPane.PLAIN_MESSAGE));
            p.setPrice(new BigDecimal(Double.toString(price)));
        }
        int amount = Integer.parseInt((String) JOptionPane.showInternalInputDialog(GUI.gui.internal, "Enter quantity", "Sale", JOptionPane.PLAIN_MESSAGE, null, null, "1"));
        this.addItem(p, amount);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        try {
            sale.complete();
            sale.setDate(new Date());
            dc.addSale(sale);
            JOptionPane.showInternalMessageDialog(GUI.gui.internal, "Sale complete", "Sale", JOptionPane.INFORMATION_MESSAGE);
            init();
        } catch (IOException | SQLException ex) {
            JOptionPane.showInternalMessageDialog(GUI.gui.internal, ex, "Sale", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(ManualSaleWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnComplete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
