/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.davidg95.JTill.jtillserver;

import io.github.davidg95.JTill.jtill.*;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class PluSettings extends javax.swing.JInternalFrame {

    private static PluSettings window;

    private final DataConnect dc;

    /**
     * Creates new form PluSettings
     */
    public PluSettings(DataConnect dc) {
        this.dc = dc;
        initComponents();
//        setIconImage(icon);
        super.setClosable(true);
        super.setIconifiable(true);
        super.setFrameIcon(new ImageIcon(GUI.icon));
        setTitle("PLU Settings");
        init();
    }

    public static void showWindow(DataConnect dc) {
        if (window == null || window.isClosed()) {
            window = new PluSettings(dc);
            GUI.gui.internal.add(window);
        }
        window.setVisible(true);
        try {
            window.setIcon(false);
            window.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(PluSettings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void init() {
        try {
            txtUPC.setText(dc.getSetting("UPC_PREFIX"));
            txtLength.setText(dc.getSetting("BARCODE_LENGTH"));

            String upc = dc.getSetting("UPC_PREFIX");
            int length = Integer.parseInt(dc.getSetting("BARCODE_LENGTH"));
            if (!upc.equals("")) {
                int lengthToAdd = length - upc.length();
                String ref = dc.getSetting("NEXT_PLU");
                for (int i = 1; i < lengthToAdd; i++) {
                    ref = 0 + ref;
                }
                String barcode = upc + ref;
                txtNext.setText(barcode);
            }

        } catch (IOException ex) {
            Logger.getLogger(PluSettings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void saveUPC() {
        String upc = txtUPC.getText();

        if (upc.equals("")) {
            JOptionPane.showMessageDialog(this, "If you do not specify a prefix, you will not be able to generate any barcodes", "UPC Prefix", JOptionPane.WARNING_MESSAGE);
        } else if (upc.length() < 6 || upc.length() > 10) {
            JOptionPane.showMessageDialog(this, "UPC Prefix must be between 6 and 10 characters long", "UPC Prefix", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (!upc.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Must only contain numbers", "UPC Prefix", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            dc.setSetting("UPC_PREFIX", upc);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex, "UPC Prefix", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void saveLength() {
        if (txtLength.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "You must sepcify a length", "Length", JOptionPane.WARNING_MESSAGE);
        } else if (!txtLength.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Must only contain numbers", "Length", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int l = Integer.parseInt(txtLength.getText());
        if (l < 8 || l > 15) {
            JOptionPane.showMessageDialog(this, "Length must be between 8 and 15", "Length", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String length = txtLength.getText();

        try {
            dc.setSetting("BARCODE_LENGTH", length);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex, "Barcode Length", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUPC = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtLength = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNext = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jLabel1.setText("UPC Company Prefix:");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel2.setText("Length for generating barcodes:");

        jLabel3.setText("Next barcode:");

        txtNext.setEditable(false);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUPC)
                            .addComponent(txtLength)
                            .addComponent(txtNext, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 81, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtUPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int prefixLength = txtUPC.getText().length();
        if (!txtLength.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Must only contain numbers", "Length", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int barcodeLength = Integer.parseInt(txtLength.getText());

        if (barcodeLength <= prefixLength) {
            JOptionPane.showMessageDialog(this, "Your barcode length must be greater than your UPC Prefix length", "Plu settings", JOptionPane.ERROR_MESSAGE);
            return;
        }
        saveUPC();
        saveLength();
        JOptionPane.showMessageDialog(this, "Settings saved", "Plu Settings", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        try {
            dc.setSetting("NEXT_PLU", "0");
            init();
        } catch (IOException ex) {
            Logger.getLogger(PluSettings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnResetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtNext;
    private javax.swing.JTextField txtUPC;
    // End of variables declaration//GEN-END:variables
}
