/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.davidg95.JTill.jtillserver;

import io.github.davidg95.JTill.jtill.*;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Window;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public final class ProductEntryDialog extends javax.swing.JDialog {

    private final DataConnect dc;
    private Plu plu;
    private Product product;
    private Category selectedCategory;
    private Department selectedDepartment;
    private Tax selectedTax;

    private String nextBarcode;

    /**
     * Creates new form ProductEntryDialog.
     *
     * @param parent the parent component.
     * @param dc the data connection.
     * @param icon the frame icon.
     */
    public ProductEntryDialog(Window parent, DataConnect dc, Image icon) {
        super(parent);
        this.dc = dc;
        initComponents();
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        setModal(true);
        setIconImage(icon);
        setLocationRelativeTo(parent);
        try {
            selectedCategory = dc.getCategory(1);
            selectedTax = dc.getTax(1);
            selectedDepartment = dc.getDepartment(1);
            btnSelectCategory.setText(selectedCategory.getName());
            btnSelectTax.setText(selectedTax.getName());
            btnSelectDepartment.setText(selectedDepartment.getName());
        } catch (IOException | SQLException | JTillException ex) {
            Logger.getLogger(ProductEntryDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        CardLayout c = (CardLayout) jPanel1.getLayout();
        c.show(jPanel1, "card2");
    }

    public static void showDialog(Component parent, DataConnect dc, Image icon) {
        Window window = null;
        if (parent instanceof Dialog || parent instanceof Frame) {
            window = (Window) parent;
        }
        new ProductEntryDialog(window, dc, icon).setVisible(true);
    }

    private void resetPanels() {
        try {
            selectedCategory = dc.getCategory(1);
            selectedTax = dc.getTax(1);
            selectedDepartment = dc.getDepartment(1);
        } catch (IOException | SQLException | JTillException ex) {
            Logger.getLogger(ProductEntryDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtPlu.setText("");

        txtName.setText("");
        txtShortName.setText("");
        txtOrderCode.setText("0");
        txtPrice.setText("");
        txtCostPrice.setText("");
        txtMinStock.setText("0");
        txtMaxStock.setText("0");
        txtComments.setText("");
        btnSelectCategory.setText(selectedCategory.getName());
        btnSelectTax.setText(selectedTax.getName());
        btnSelectDepartment.setText(selectedDepartment.getName());

        txtOpenName.setText("");
        txtOpenShort.setText("");
        txtOpenComments.setText("");
        btnOpenCategory.setText(selectedCategory.getName());
        btnOpenTax.setText(selectedTax.getName());
        btnOpenDepartment.setText(selectedDepartment.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panProduct = new javax.swing.JPanel();
        btnSelectDepartment = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtOrderCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComments = new javax.swing.JTextArea();
        btnAddProduct = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtShortName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCostPrice = new javax.swing.JTextField();
        txtMinStock = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaxStock = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnSelectCategory = new javax.swing.JButton();
        btnSelectTax = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panOpenProduct = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtOpenName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtOpenShort = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnOpenDepartment = new javax.swing.JButton();
        btnOpenCategory = new javax.swing.JButton();
        btnOpenTax = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOpenComments = new javax.swing.JTextArea();
        btnAddOpen = new javax.swing.JButton();
        btnBack2 = new javax.swing.JButton();
        panBarcode = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPlu = new javax.swing.JTextField();
        btnEnter = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        radNew = new javax.swing.JRadioButton();
        radCopy = new javax.swing.JRadioButton();
        radNewOpen = new javax.swing.JRadioButton();
        chkNext = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New Product");
        setResizable(false);

        jPanel1.setLayout(new java.awt.CardLayout());

        btnSelectDepartment.setText("Select Department");
        btnSelectDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectDepartmentActionPerformed(evt);
            }
        });

        jLabel13.setText("Order Code:");

        txtOrderCode.setText("0");

        jLabel5.setText("Comments:");

        txtComments.setColumns(20);
        txtComments.setRows(5);
        jScrollPane1.setViewportView(txtComments);

        btnAddProduct.setText("Create");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel6.setText("Short Name:");

        jLabel7.setText("Category:");

        jLabel8.setText("Tax Class:");

        jLabel9.setText("Cost Price (£):");

        txtMinStock.setText("0");

        jLabel10.setText("Min Stock Level:");

        jLabel11.setText("Max Stock Level:");

        jLabel2.setText("Product Name:");

        txtMaxStock.setText("0");

        btnSelectCategory.setText("Select Category");
        btnSelectCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCategoryActionPerformed(evt);
            }
        });

        btnSelectTax.setText("Select Tax");
        btnSelectTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectTaxActionPerformed(evt);
            }
        });

        jLabel12.setText("Department:");

        jLabel14.setText("Price (£):");

        javax.swing.GroupLayout panProductLayout = new javax.swing.GroupLayout(panProduct);
        panProduct.setLayout(panProductLayout);
        panProductLayout.setHorizontalGroup(
            panProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProductLayout.createSequentialGroup()
                .addGroup(panProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panProductLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCostPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panProductLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMinStock, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaxStock, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panProductLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panProductLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(panProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel5)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panProductLayout.createSequentialGroup()
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9))
                                .addComponent(txtOrderCode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panProductLayout.createSequentialGroup()
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtShortName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnSelectDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSelectCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSelectTax, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panProductLayout.setVerticalGroup(
            panProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtShortName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtOrderCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCostPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMinStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtMaxStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectDepartment)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectCategory)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectTax)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(panProduct, "card3");

        jLabel3.setText("Product Name:");

        jLabel4.setText("Short Name:");

        jLabel15.setText("Department:");

        jLabel16.setText("Category:");

        jLabel17.setText("Tax:");

        btnOpenDepartment.setText("Select Department");
        btnOpenDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDepartmentActionPerformed(evt);
            }
        });

        btnOpenCategory.setText("Select Category");
        btnOpenCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenCategoryActionPerformed(evt);
            }
        });

        btnOpenTax.setText("Select Tax");
        btnOpenTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenTaxActionPerformed(evt);
            }
        });

        jLabel18.setText("Comments:");

        txtOpenComments.setColumns(20);
        txtOpenComments.setRows(5);
        jScrollPane2.setViewportView(txtOpenComments);

        btnAddOpen.setText("Create");
        btnAddOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOpenActionPerformed(evt);
            }
        });

        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panOpenProductLayout = new javax.swing.GroupLayout(panOpenProduct);
        panOpenProduct.setLayout(panOpenProductLayout);
        panOpenProductLayout.setHorizontalGroup(
            panOpenProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOpenProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panOpenProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panOpenProductLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panOpenProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panOpenProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(btnOpenTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panOpenProductLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOpenName, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOpenShort, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panOpenProductLayout.createSequentialGroup()
                        .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panOpenProductLayout.setVerticalGroup(
            panOpenProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOpenProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panOpenProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOpenName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtOpenShort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panOpenProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(btnOpenDepartment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panOpenProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(btnOpenCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panOpenProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(btnOpenTax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panOpenProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(panOpenProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddOpen, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(btnBack2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(panOpenProduct, "card4");

        jLabel1.setText("Enter Barcode:");

        txtPlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPluActionPerformed(evt);
            }
        });

        btnEnter.setText("Create");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        buttonGroup1.add(radNew);
        radNew.setSelected(true);
        radNew.setText("Create Standard Product");

        buttonGroup1.add(radCopy);
        radCopy.setText("Copy details from existing");

        buttonGroup1.add(radNewOpen);
        radNewOpen.setText("Create Open Product");

        chkNext.setText("Assign next avaliable");
        chkNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBarcodeLayout = new javax.swing.GroupLayout(panBarcode);
        panBarcode.setLayout(panBarcodeLayout);
        panBarcodeLayout.setHorizontalGroup(
            panBarcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBarcodeLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(panBarcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBarcodeLayout.createSequentialGroup()
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBarcodeLayout.createSequentialGroup()
                        .addGroup(panBarcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panBarcodeLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPlu, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkNext))
                            .addGroup(panBarcodeLayout.createSequentialGroup()
                                .addGroup(panBarcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panBarcodeLayout.createSequentialGroup()
                                        .addComponent(radNew)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radNewOpen)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radCopy)))
                        .addGap(39, 39, 39))))
        );
        panBarcodeLayout.setVerticalGroup(
            panBarcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBarcodeLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(panBarcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkNext))
                .addGap(18, 18, 18)
                .addGroup(panBarcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radNew)
                    .addComponent(radCopy)
                    .addComponent(radNewOpen))
                .addGap(18, 18, 18)
                .addComponent(btnEnter)
                .addGap(98, 98, 98)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(panBarcode, "card2");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectDepartmentActionPerformed
        Department d = DepartmentSelectDialog.showDialog(this, dc);
        if (d != null) {
            selectedDepartment = d;
            btnSelectDepartment.setText(selectedDepartment.getName());
        }
    }//GEN-LAST:event_btnSelectDepartmentActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        String name = txtName.getText();
        String shortName = txtShortName.getText();
        String val = txtOrderCode.getText();
        if (!Utilities.isNumber(val)) {
            JOptionPane.showMessageDialog(this, "Not all fields have been filled out correctly", "Create New Product", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int orderCode = Integer.parseInt(val);
        Category category = selectedCategory;
        Tax tax = selectedTax;
        Department dep = selectedDepartment;
        String comments = txtComments.getText();
        if (!Utilities.isNumber(txtPrice.getText())) {
            JOptionPane.showMessageDialog(this, "Not all fields have been filled out correctly", "Create New Product", JOptionPane.ERROR_MESSAGE);
            return;
        }
        BigDecimal price = new BigDecimal(txtPrice.getText());
        if (price.compareTo(BigDecimal.ZERO) < 0) {
            JOptionPane.showMessageDialog(this, "Not all fields have been filled out correctly", "Create New Product", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Utilities.isNumber(txtCostPrice.getText())) {
            JOptionPane.showMessageDialog(this, "Not all fields have been filled out correctly", "Create New Product", JOptionPane.ERROR_MESSAGE);
            return;
        }
        BigDecimal costPrice = new BigDecimal(txtCostPrice.getText());
        if (costPrice.compareTo(BigDecimal.ZERO) < 0) {
            JOptionPane.showMessageDialog(this, "Not all fields have been filled out correctly", "Create New Product", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Utilities.isNumber(txtMinStock.getText())) {
            JOptionPane.showMessageDialog(this, "Not all fields have been filled out correctly", "Create New Product", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int minStock = Integer.parseInt(txtMinStock.getText());
        if (minStock < 0) {
            JOptionPane.showMessageDialog(this, "Not all fields have been filled out correctly", "Create New Product", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Utilities.isNumber(txtMaxStock.getText())) {
            JOptionPane.showMessageDialog(this, "Not all fields have been filled out correctly", "Create New Product", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int maxStock = Integer.parseInt(txtMaxStock.getText());
        if (maxStock < 0) {
            JOptionPane.showMessageDialog(this, "Not all fields have been filled out correctly", "Create New Product", JOptionPane.ERROR_MESSAGE);
            return;
        }
        product = new Product(name, shortName, orderCode, category.getId(), dep.getId(), comments, tax.getId(), false, price, costPrice, 0, minStock, maxStock, 0);
        try {
            product = dc.addProductAndPlu(product, plu);
            if (nextBarcode != null) {
                dc.setSetting("NEXT_PLU", nextBarcode);
                nextBarcode = null;
            }
            JOptionPane.showMessageDialog(this, "New product has been created", "New Product", JOptionPane.INFORMATION_MESSAGE);
            resetPanels();
            CardLayout c = (CardLayout) jPanel1.getLayout();
            c.show(jPanel1, "card2");
            txtPlu.requestFocus();
        } catch (HeadlessException | IOException | NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex, "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CardLayout c = (CardLayout) jPanel1.getLayout();
        c.show(jPanel1, "card2");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSelectCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCategoryActionPerformed
        Category c = CategorySelectDialog.showDialog(this, dc);
        if (c != null) {
            selectedCategory = c;
            btnSelectCategory.setText(selectedCategory.getName());
        }
    }//GEN-LAST:event_btnSelectCategoryActionPerformed

    private void btnSelectTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectTaxActionPerformed
        Tax t = TaxSelectDialog.showDialog(this, dc);
        if (t != null) {
            selectedTax = t;
            btnSelectTax.setText(selectedTax.getName());
        }
    }//GEN-LAST:event_btnSelectTaxActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        try {
            if (chkNext.isSelected()) {
                String upc = dc.getSetting("UPC_PREFIX"); //Get the UPC Prefix
                int length = Integer.parseInt(dc.getSetting("BARCODE_LENGTH")); //Get the barcode length
                if (!upc.equals("")) { //Check that the UPC has been set
                    while (true) {
                        int lengthToAdd = length - upc.length(); //Work out how many more digits need added
                        String ref = dc.getSetting("NEXT_PLU"); //Get the next PLU number
                        int n = Integer.parseInt(ref);
                        n++;
                        nextBarcode = Integer.toString(n); // Increase it then convert it to a String
                        lengthToAdd -= ref.length(); //Subtract the length to find out how many digits need added
                        for (int i = 1; i <= lengthToAdd; i++) {
                            ref = 0 + ref; //Pad it out with zero's to make up the length
                        }
                        String barcode = upc + ref; //Join them all together
                        if (!dc.checkBarcode(barcode)) { //Check the barcode is not already int use
                            plu = new Plu(barcode, 0); //Create the new PLU
                            break; //break from the while loop
                        } else {
                            dc.setSetting("NEXT_PLU", nextBarcode); //If it is in use, set the next plu and loop again
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "You have not specified a UPC Company Prefix. This must be done before generating your own barcodes. Go to Setup -> Plu Settings to do this.", "Generate Barcode", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                //If excecution reaches here, it means an unsude PLU as been generated
            } else {
                //Get the PLu from the user, check what they entered is valid
                if (txtPlu.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "You must enter a barcode", "New Product", JOptionPane.WARNING_MESSAGE);
                    return;
                } else if (txtPlu.getText().length() < 8 || txtPlu.getText().length() > 15) {
                    JOptionPane.showMessageDialog(this, "Barcodes must be between 8 and 15 characters long", "New Product", JOptionPane.WARNING_MESSAGE);
                    return;
                } else if (!txtPlu.getText().matches("[0-9]+")) {
                    JOptionPane.showMessageDialog(this, "Must only contain numbers", "New Product", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                if (dc.checkBarcode(txtPlu.getText())) {
                    JOptionPane.showMessageDialog(this, "Barcode is already in use", "Barcode in use", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                plu = new Plu(txtPlu.getText(), 0);
            }
            //Check what kinda of product they want to create
            if (radNew.isSelected()) { //Create a new standard product
                txtPlu.setText("");
                CardLayout c = (CardLayout) jPanel1.getLayout();
                c.show(jPanel1, "card3");
                txtName.requestFocus();
            } else if (radNewOpen.isSelected()) { //Create a new open price product
                txtPlu.setText("");
                CardLayout c = (CardLayout) jPanel1.getLayout();
                c.show(jPanel1, "card4");
                txtOpenName.requestFocus();
            } else {
                Product toCopy = ProductSelectDialog.showDialog(this, dc); //Copy details from an existing product
                if (toCopy != null) {
                    dc.addProductAndPlu(toCopy, plu);
                    JOptionPane.showMessageDialog(this, "New Plu created", "New Plu", JOptionPane.INFORMATION_MESSAGE);
                    txtPlu.setText("");
                    radNew.setSelected(true);
                    txtPlu.requestFocus();
                }
            }
        } catch (IOException | SQLException ex) {
            Logger.getLogger(ProductEntryDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void txtPluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPluActionPerformed
        btnEnter.doClick();
    }//GEN-LAST:event_txtPluActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        CardLayout c = (CardLayout) jPanel1.getLayout();
        c.show(jPanel1, "card2");
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnOpenDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDepartmentActionPerformed
        Department d = DepartmentSelectDialog.showDialog(this, dc);
        if (d != null) {
            selectedDepartment = d;
            btnOpenDepartment.setText(selectedDepartment.getName());
        }
    }//GEN-LAST:event_btnOpenDepartmentActionPerformed

    private void btnOpenCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenCategoryActionPerformed
        Category c = CategorySelectDialog.showDialog(this, dc);
        if (c != null) {
            selectedCategory = c;
            btnOpenCategory.setText(selectedCategory.getName());
        }
    }//GEN-LAST:event_btnOpenCategoryActionPerformed

    private void btnOpenTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenTaxActionPerformed
        Tax t = TaxSelectDialog.showDialog(this, dc);
        if (t != null) {
            selectedTax = t;
            btnOpenTax.setText(selectedTax.getName());
        }
    }//GEN-LAST:event_btnOpenTaxActionPerformed

    private void btnAddOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOpenActionPerformed
        String name = txtOpenName.getText();
        String shortName = txtOpenShort.getText();
        Category category = selectedCategory;
        Tax tax = selectedTax;
        Department dep = selectedDepartment;
        String comments = txtOpenComments.getText();
        try {
            product = new Product(name, shortName, 0, category.getId(), dep.getId(), comments, tax.getId(), true);
            plu.setProduct(product.getId());
            product = dc.addProductAndPlu(product, plu);
            if (chkNext.isSelected()) {
                dc.setSetting("NEXT_PLU", nextBarcode);
            }
            JOptionPane.showMessageDialog(this, "New product has been created", "New Product", JOptionPane.INFORMATION_MESSAGE);
            resetPanels();
            CardLayout c = (CardLayout) jPanel1.getLayout();
            c.show(jPanel1, "card2");
            txtPlu.requestFocus();
        } catch (HeadlessException | IOException | NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex, "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddOpenActionPerformed

    private void chkNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNextActionPerformed
        txtPlu.setEnabled(!chkNext.isSelected());
    }//GEN-LAST:event_chkNextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOpen;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnOpenCategory;
    private javax.swing.JButton btnOpenDepartment;
    private javax.swing.JButton btnOpenTax;
    private javax.swing.JButton btnSelectCategory;
    private javax.swing.JButton btnSelectDepartment;
    private javax.swing.JButton btnSelectTax;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panBarcode;
    private javax.swing.JPanel panOpenProduct;
    private javax.swing.JPanel panProduct;
    private javax.swing.JRadioButton radCopy;
    private javax.swing.JRadioButton radNew;
    private javax.swing.JRadioButton radNewOpen;
    private javax.swing.JTextArea txtComments;
    private javax.swing.JTextField txtCostPrice;
    private javax.swing.JTextField txtMaxStock;
    private javax.swing.JTextField txtMinStock;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtOpenComments;
    private javax.swing.JTextField txtOpenName;
    private javax.swing.JTextField txtOpenShort;
    private javax.swing.JTextField txtOrderCode;
    private javax.swing.JTextField txtPlu;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtShortName;
    // End of variables declaration//GEN-END:variables
}
