/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.davidg95.JTill.jtillserver;

import io.github.davidg95.JTill.jtill.*;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class SettingsWindow extends javax.swing.JFrame {

    public static SettingsWindow frame;

    private final DataConnectInterface dbConn;

    private boolean editNetwork = false;

    private boolean editDatabase = false;

    /**
     * Creates new form Settings
     */
    public SettingsWindow(DataConnectInterface dc) {
        this.dbConn = dc;
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public static void initWindow() {
//        if (frame != null) {
//            frame = new SettingsWindow();
//            frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//        }
    }

    public static void showSettingsWindow(DataConnectInterface dc) {
        if (frame == null) {
            frame = new SettingsWindow(dc);
            frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        }
        update();
        frame.setVisible(true);
    }

    public static void update() {
        frame.init();
    }

    private void init() {
        txtPort.setText(DBConnect.PORT + "");
        txtMaxConn.setText(DBConnect.MAX_CONNECTIONS + "");
        txtMaxQueued.setText(DBConnect.MAX_QUEUE + "");
        txtAddress.setText(DBConnect.DB_ADDRESS);
        txtUsername.setText(DBConnect.DB_USERNAME);
        txtPassword.setText(DBConnect.DB_PASSWORD);
        chkLogOut.setSelected(TillInitData.initData.autoLogout);
        txtLogonMessage.setText(TillInitData.initData.logonScreenMessage);
        if (TillInitData.initData.logoutTimeout == -1) {
            chkLogoutTimeout.setSelected(false);
            txtLogoutTimeout.setText("");
            txtLogoutTimeout.setEnabled(false);
        } else {
            chkLogoutTimeout.setSelected(true);
            txtLogoutTimeout.setText(TillInitData.initData.logoutTimeout + "");
            txtLogoutTimeout.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNetwork = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        txtMaxConn = new javax.swing.JTextField();
        txtMaxQueued = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEditNetwork = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        panelDatabase = new javax.swing.JPanel();
        txtAddress = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEditDatabase = new javax.swing.JButton();
        panelSecurity = new javax.swing.JPanel();
        txtLogoutTimeout = new javax.swing.JTextField();
        chkLogOut = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        chkLogoutTimeout = new javax.swing.JCheckBox();
        btnSaveSecurity = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnDatabaseDefault = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnLogonMessage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLogonMessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JTill Settings");
        setIconImage(TillServer.getIcon());

        panelNetwork.setBorder(javax.swing.BorderFactory.createTitledBorder("Network Options"));

        jLabel1.setText("Port Number:");
        jLabel1.setEnabled(false);

        txtPort.setEnabled(false);

        txtMaxConn.setEnabled(false);

        txtMaxQueued.setEnabled(false);

        jLabel2.setText("Maximum Connections:");
        jLabel2.setEnabled(false);

        jLabel3.setText("Maximum Queued Connections:");
        jLabel3.setEnabled(false);

        javax.swing.GroupLayout panelNetworkLayout = new javax.swing.GroupLayout(panelNetwork);
        panelNetwork.setLayout(panelNetworkLayout);
        panelNetworkLayout.setHorizontalGroup(
            panelNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNetworkLayout.createSequentialGroup()
                .addGroup(panelNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaxQueued)
                    .addComponent(txtMaxConn)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelNetworkLayout.setVerticalGroup(
            panelNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNetworkLayout.createSequentialGroup()
                .addGroup(panelNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaxConn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaxQueued, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)))
        );

        btnEditNetwork.setText("Edit Network Options");
        btnEditNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditNetworkActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        panelDatabase.setBorder(javax.swing.BorderFactory.createTitledBorder("Database Options"));
        panelDatabase.setEnabled(false);

        txtAddress.setEnabled(false);

        txtUsername.setEnabled(false);

        txtPassword.setEnabled(false);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        jLabel4.setText("Address:");
        jLabel4.setEnabled(false);

        jLabel5.setText("Username:");
        jLabel5.setEnabled(false);

        jLabel6.setText("Password:");
        jLabel6.setEnabled(false);

        javax.swing.GroupLayout panelDatabaseLayout = new javax.swing.GroupLayout(panelDatabase);
        panelDatabase.setLayout(panelDatabaseLayout);
        panelDatabaseLayout.setHorizontalGroup(
            panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatabaseLayout.createSequentialGroup()
                .addGroup(panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress)
                    .addComponent(txtUsername)
                    .addComponent(txtPassword)))
        );
        panelDatabaseLayout.setVerticalGroup(
            panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatabaseLayout.createSequentialGroup()
                .addGroup(panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)))
        );

        btnEditDatabase.setText("Edit Database Options");
        btnEditDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDatabaseActionPerformed(evt);
            }
        });

        panelSecurity.setBorder(javax.swing.BorderFactory.createTitledBorder("Security"));

        txtLogoutTimeout.setText("30");

        chkLogOut.setText("Log Out After Sale Is Complete");

        jLabel8.setText("seconds");

        chkLogoutTimeout.setSelected(true);
        chkLogoutTimeout.setText("Enabled");
        chkLogoutTimeout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLogoutTimeoutActionPerformed(evt);
            }
        });

        btnSaveSecurity.setText("Save Changes");
        btnSaveSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSecurityActionPerformed(evt);
            }
        });

        jLabel7.setText("Automatic Logout Timeout:");

        javax.swing.GroupLayout panelSecurityLayout = new javax.swing.GroupLayout(panelSecurity);
        panelSecurity.setLayout(panelSecurityLayout);
        panelSecurityLayout.setHorizontalGroup(
            panelSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chkLogOut)
            .addGroup(panelSecurityLayout.createSequentialGroup()
                .addGroup(panelSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSaveSecurity)
                    .addGroup(panelSecurityLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLogoutTimeout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkLogoutTimeout))
        );
        panelSecurityLayout.setVerticalGroup(
            panelSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSecurityLayout.createSequentialGroup()
                .addComponent(chkLogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtLogoutTimeout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(chkLogoutTimeout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveSecurity))
        );

        btnDatabaseDefault.setText("Reset To Default");
        btnDatabaseDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatabaseDefaultActionPerformed(evt);
            }
        });

        jLabel9.setText("Logon Screen Message:");

        btnLogonMessage.setText("Save");
        btnLogonMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogonMessageActionPerformed(evt);
            }
        });

        txtLogonMessage.setColumns(20);
        txtLogonMessage.setRows(5);
        txtLogonMessage.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtLogonMessage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEditDatabase)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDatabaseDefault, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(panelNetwork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditNetwork)
                            .addComponent(panelDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogonMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(btnLogonMessage))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditNetwork)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditDatabase)
                    .addComponent(btnDatabaseDefault))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditNetworkActionPerformed
        if (editNetwork) {
            int port = Integer.parseInt(txtPort.getText());
            int max = Integer.parseInt(txtMaxConn.getText());
            int queue = Integer.parseInt(txtMaxQueued.getText());
            if (port < 0 || port > 65535) {
                JOptionPane.showMessageDialog(this, "Please enter a port value between 0 and 65535", "Server Options", JOptionPane.PLAIN_MESSAGE);
            } else if (max < 0 || queue < 0) {
                JOptionPane.showMessageDialog(this, "Please enter a value greater than 0", "Server Options", JOptionPane.PLAIN_MESSAGE);
            } else {
                DBConnect.PORT = port;
                DBConnect.MAX_CONNECTIONS = max;
                DBConnect.MAX_QUEUE = queue;
                if (dbConn instanceof DBConnect) {
                    DBConnect db = (DBConnect) dbConn;
                    db.saveProperties();
                }
            }
            for (Component c : panelNetwork.getComponents()) {
                c.setEnabled(false);
            }
            btnEditNetwork.setText("Edit Network Options");
            editNetwork = false;
            JOptionPane.showMessageDialog(this, "Changes will take place next time server restarts", "Server Options", JOptionPane.PLAIN_MESSAGE);
        } else {
            for (Component c : panelNetwork.getComponents()) {
                c.setEnabled(true);
            }
            btnEditNetwork.setText("Save");
            editNetwork = true;
        }
    }//GEN-LAST:event_btnEditNetworkActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed

    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnEditDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDatabaseActionPerformed
        if (editDatabase) {
            String address = txtAddress.getText();
            String username = txtUsername.getText();
            String password = new String(txtPassword.getPassword());
            DBConnect.DB_ADDRESS = address;
            DBConnect.DB_USERNAME = username;
            DBConnect.DB_PASSWORD = password;
            if (dbConn instanceof DBConnect) {
                DBConnect db = (DBConnect) dbConn;
                db.saveProperties();
            }
            for (Component c : panelDatabase.getComponents()) {
                c.setEnabled(false);
            }
            btnEditDatabase.setText("Edit Database Options");
            editDatabase = false;
            JOptionPane.showMessageDialog(this, "Changes will take place next time server restarts", "Server Options", JOptionPane.PLAIN_MESSAGE);
        } else {
            for (Component c : panelDatabase.getComponents()) {
                c.setEnabled(true);
            }
            btnEditDatabase.setText("Save");
            editDatabase = true;
        }
    }//GEN-LAST:event_btnEditDatabaseActionPerformed

    private void btnSaveSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSecurityActionPerformed
        TillInitData.initData.autoLogout = chkLogOut.isSelected();
        if (chkLogoutTimeout.isSelected()) {
            TillInitData.initData.logoutTimeout = Integer.parseInt(txtLogoutTimeout.getText());
        } else {
            TillInitData.initData.logoutTimeout = -1;
        }
        TillInitData.initData.setLogoutTimeout(TillInitData.initData.logoutTimeout);
        TillInitData.initData.setAutoLogout(TillInitData.initData.autoLogout);
        if (dbConn instanceof DBConnect) {
            DBConnect db = (DBConnect) dbConn;
            db.saveProperties();
        }
    }//GEN-LAST:event_btnSaveSecurityActionPerformed

    private void chkLogoutTimeoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLogoutTimeoutActionPerformed
        txtLogoutTimeout.setEnabled(chkLogoutTimeout.isSelected());
    }//GEN-LAST:event_chkLogoutTimeoutActionPerformed

    private void btnDatabaseDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatabaseDefaultActionPerformed
        DBConnect.DB_ADDRESS = DBConnect.defaultAddress;
        DBConnect.DB_USERNAME = DBConnect.defaultUsername;
        DBConnect.DB_PASSWORD = DBConnect.defaultPassword;
        txtAddress.setText(DBConnect.DB_ADDRESS);
        txtUsername.setText(DBConnect.DB_USERNAME);
        txtPassword.setText(DBConnect.DB_PASSWORD);
        if (dbConn instanceof DBConnect) {
            DBConnect db = (DBConnect) dbConn;
            db.saveProperties();
        }
        JOptionPane.showMessageDialog(this, "Changes will take place next time server restarts", "Server Options", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnDatabaseDefaultActionPerformed

    private void btnLogonMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogonMessageActionPerformed
        TillInitData.initData.setLogonScreenMessage(txtLogonMessage.getText());
    }//GEN-LAST:event_btnLogonMessageActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDatabaseDefault;
    private javax.swing.JButton btnEditDatabase;
    private javax.swing.JButton btnEditNetwork;
    private javax.swing.JButton btnLogonMessage;
    private javax.swing.JButton btnSaveSecurity;
    private javax.swing.JCheckBox chkLogOut;
    private javax.swing.JCheckBox chkLogoutTimeout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDatabase;
    private javax.swing.JPanel panelNetwork;
    private javax.swing.JPanel panelSecurity;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextArea txtLogonMessage;
    private javax.swing.JTextField txtLogoutTimeout;
    private javax.swing.JTextField txtMaxConn;
    private javax.swing.JTextField txtMaxQueued;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
