/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.davidg95.JTill.jtillserver;

import io.github.davidg95.JTill.jtill.*;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author 1301480
 */
public class StaffDialog extends javax.swing.JDialog {

    private final Logger log = Logger.getGlobal();

    private static JDialog dialog;
    private static Staff staff;

    private DataConnect dc;
    private Staff s;
    private boolean editMode;

    /**
     * Creates new form StaffDialog
     *
     * @param parent the parent window.
     * @param dc the data connection.
     * @param manager force the staff to be a manager.
     */
    public StaffDialog(Window parent, DataConnect dc, boolean manager) {
        super(parent);
        editMode = false;
        this.dc = dc;
        initComponents();
        if(manager){
            cmbPosition.setSelectedIndex(2);
            cmbPosition.setEnabled(false);
        }
        this.setLocationRelativeTo(parent);
        this.setModal(true);
    }

    /**
     * Creates new form StaffDialog
     *
     * @param parent parent window.
     * @param dc the data connection.
     * @param staff staff getting edited.
     */
    public StaffDialog(Window parent, DataConnect dc, Staff staff) {
        super(parent);
        initComponents();
        editMode = true;
        this.s = staff;
        this.dc = dc;
        this.setLocationRelativeTo(parent);
        this.setModal(true);
        txtName.setText(s.getName());
        txtUsername.setText(s.getUsername());
        btnAdd.setText("Save Changes");
        cmbPosition.setSelectedItem(staff.getPosition());
        this.setTitle("Staff Member " + staff.getName());
    }

    public static Staff showNewStaffDialog(Component parent, DataConnect dc, boolean manager) {
        Window window = null;
        if (parent instanceof Dialog || parent instanceof Frame) {
            window = (Window) parent;
        }
        dialog = new StaffDialog(window, dc, manager);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        staff = null;
        dialog.setVisible(true);
        return staff;
    }
    
    public static Staff showNewStaffDialog(Component parent, DataConnect dc) {
        return showNewStaffDialog(parent, dc, false);
    }

    public static Staff showEditStaffDialog(Component parent, DataConnect dc, Staff s) {
        Window window = null;
        if (parent instanceof Dialog || parent instanceof Frame) {
            window = (Window) parent;
        }
        dialog = new StaffDialog(window, dc, s);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        staff = s;
        dialog.setVisible(true);
        return staff;
    }

    private void showError(Exception e) {
        JOptionPane.showMessageDialog(this, e, "Staff", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        cmbPosition = new javax.swing.JComboBox<>();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtPasswordConfirm = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtWage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Staff");
        setResizable(false);

        cmbPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Assisstant", "Supervisor", "Manager", "Area Manager"}));

        txtPasswordConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordConfirmActionPerformed(evt);
            }
        });

        jLabel1.setLabelFor(txtName);
        jLabel1.setText("Name:");

        jLabel2.setLabelFor(cmbPosition);
        jLabel2.setText("Position:");

        jLabel3.setLabelFor(txtUsername);
        jLabel3.setText("Username:");

        jLabel4.setLabelFor(txtPassword);
        jLabel4.setText("Password:");

        jLabel5.setLabelFor(txtPasswordConfirm);
        jLabel5.setText("Confirm Password:");

        btnAdd.setText("Add Employee");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel6.setText("Wage:");

        txtWage.setText("0.00");
        txtWage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtWageFocusGained(evt);
            }
        });
        txtWage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(btnAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(cmbPosition, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword)
                            .addComponent(txtPasswordConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(txtWage))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String name = txtName.getText();
        String username = txtUsername.getText();
        try {
            if (dc.checkUsername(username)) {
                JOptionPane.showMessageDialog(this, "Username already in use", "New Staff", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (IOException | SQLException ex) {
            log.log(Level.SEVERE, null, ex);
        }
        int position = cmbPosition.getSelectedIndex() + 1;
        if (!editMode) {
            if (new String(txtPassword.getPassword()).equals(new String(txtPasswordConfirm.getPassword()))) {
                String password = new String(txtPassword.getPassword());
                if (!Utilities.isNumber(txtWage.getText())) {
                    JOptionPane.showMessageDialog(this, "Not all fields have been filled out correctly", "Create New Staff", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                double wage = Double.parseDouble(txtWage.getText());
                if (wage <= 0) {
                    JOptionPane.showMessageDialog(this, "Wage must be greater than 0", "Create New Staff", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                staff = new Staff(name, position, username, password, wage);
                try {
                    Staff s = dc.addStaff(staff);
                } catch (SQLException | IOException ex) {
                    showError(ex);
                }
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Passwords do not match", "New Staff", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            try {
                staff.setName(name);
                staff.setUsername(username);
                dc.updateStaff(staff);
                this.setVisible(false);
            } catch (IOException | StaffNotFoundException | SQLException ex) {
                showError(ex);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtPasswordConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordConfirmActionPerformed
        btnAdd.doClick();
    }//GEN-LAST:event_txtPasswordConfirmActionPerformed

    private void txtWageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWageActionPerformed
        btnAdd.doClick();
    }//GEN-LAST:event_txtWageActionPerformed

    private void txtWageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWageFocusGained
        txtWage.setSelectionStart(0);
        txtWage.setSelectionEnd(txtWage.getText().length());
    }//GEN-LAST:event_txtWageFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JComboBox<String> cmbPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblError;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordConfirm;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtWage;
    // End of variables declaration//GEN-END:variables
}
