/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.davidg95.JTill.jtillserver;

import io.github.davidg95.JTill.jtill.*;
import java.awt.Component;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David
 */
public class VoucherWindow extends javax.swing.JFrame {

    private static VoucherWindow frame;

    private final DataConnect dc;

    private Voucher voucher;

    private final DefaultTableModel model;
    private List<Voucher> currentTableContents;

    /**
     * Creates new form VoucherWindow
     */
    public VoucherWindow(DataConnect dc) {
        this.dc = dc;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        currentTableContents = new ArrayList<>();
        model = (DefaultTableModel) tableVouchers.getModel();
        showAllVouchers();
        init();
    }

    public static void showVoucherWindow(DataConnect dc) {
        if (frame == null) {
            frame = new VoucherWindow(dc);
            frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        }
        frame.setVisible(true);
    }

    public static void update() {
        if (frame != null) {
            frame.showAllVouchers();
            frame.init();
        }
    }

    private void init() {

    }

    private void updateTable() {
        model.setRowCount(0);

        for (Voucher v : currentTableContents) {
            Object[] s = new Object[]{v.getId(), v.getName()};
            model.addRow(s);
        }

        tableVouchers.setModel(model);
    }

    private void showAllVouchers() {
        try {
            currentTableContents = dc.getAllVouchers();
        } catch (IOException | SQLException ex) {
            showError(ex);
        }
        updateTable();
    }

    private void setCurrentVoucher(Voucher v) {
        if (v != null) {
            voucher = v;
            txtName.setText(v.getName());
        } else {
            txtName.setText("");
            voucher = null;
        }
    }

    private void showError(Exception e) {
        JOptionPane.showMessageDialog(this, e, "Products", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupXonYgetZ = new javax.swing.ButtonGroup();
        buttonGroupBOGOF = new javax.swing.ButtonGroup();
        buttonGroupVoucher = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelVouchers = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVouchers = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnAddNew = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        panelConditions = new javax.swing.JPanel();
        panelXOffYGetZ = new javax.swing.JPanel();
        lblXYZ1 = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        lblXYZ2 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        lblXYZ3 = new javax.swing.JLabel();
        radPercent = new javax.swing.JRadioButton();
        radMoney = new javax.swing.JRadioButton();
        txtValueOff = new javax.swing.JTextField();
        radXOffYGetZ = new javax.swing.JRadioButton();
        panelMultibuy = new javax.swing.JPanel();
        lblMultibuy1 = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        lblMultibuy2 = new javax.swing.JLabel();
        btnSearchItem = new javax.swing.JButton();
        lblMultibuy3 = new javax.swing.JLabel();
        txtBOGOFValueOff = new javax.swing.JTextField();
        radBOGOFPercent = new javax.swing.JRadioButton();
        radBOGOFMoney = new javax.swing.JRadioButton();
        radMultibuy = new javax.swing.JRadioButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vouchers");

        tableVouchers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVouchers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVouchersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableVouchers);
        if (tableVouchers.getColumnModel().getColumnCount() > 0) {
            tableVouchers.getColumnModel().getColumn(0).setResizable(false);
            tableVouchers.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setText("Name:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btnAddNew.setText("Add");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVouchersLayout = new javax.swing.GroupLayout(panelVouchers);
        panelVouchers.setLayout(panelVouchersLayout);
        panelVouchersLayout.setHorizontalGroup(
            panelVouchersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVouchersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVouchersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVouchersLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddNew))
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelVouchersLayout.setVerticalGroup(
            panelVouchersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVouchersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVouchersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVouchersLayout.createSequentialGroup()
                        .addGroup(panelVouchersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddNew))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vouchers", panelVouchers);

        panelXOffYGetZ.setBorder(javax.swing.BorderFactory.createTitledBorder("X on Y get Z off"));

        lblXYZ1.setText("If");

        lblXYZ2.setText("is spent on");

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblXYZ3.setText("then take");

        buttonGroupXonYgetZ.add(radPercent);
        radPercent.setSelected(true);
        radPercent.setText("percentage off");

        buttonGroupXonYgetZ.add(radMoney);
        radMoney.setText("money off");

        javax.swing.GroupLayout panelXOffYGetZLayout = new javax.swing.GroupLayout(panelXOffYGetZ);
        panelXOffYGetZ.setLayout(panelXOffYGetZLayout);
        panelXOffYGetZLayout.setHorizontalGroup(
            panelXOffYGetZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXOffYGetZLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblXYZ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblXYZ2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblXYZ3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValueOff, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelXOffYGetZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radMoney)
                    .addComponent(radPercent)))
        );
        panelXOffYGetZLayout.setVerticalGroup(
            panelXOffYGetZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXOffYGetZLayout.createSequentialGroup()
                .addGroup(panelXOffYGetZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblXYZ1)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblXYZ2)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblXYZ3)
                    .addComponent(radPercent)
                    .addComponent(txtValueOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radMoney)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        buttonGroupVoucher.add(radXOffYGetZ);
        radXOffYGetZ.setSelected(true);
        radXOffYGetZ.setText("X on Y get Z off");
        radXOffYGetZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radXOffYGetZActionPerformed(evt);
            }
        });

        panelMultibuy.setBorder(javax.swing.BorderFactory.createTitledBorder("Multibuy"));
        panelMultibuy.setEnabled(false);

        lblMultibuy1.setText("If");
        lblMultibuy1.setEnabled(false);

        txtNumber.setEnabled(false);

        lblMultibuy2.setText("of item");
        lblMultibuy2.setEnabled(false);

        btnSearchItem.setText("Search Item");
        btnSearchItem.setEnabled(false);

        lblMultibuy3.setText("is purchased then take");
        lblMultibuy3.setEnabled(false);

        txtBOGOFValueOff.setEnabled(false);

        buttonGroupBOGOF.add(radBOGOFPercent);
        radBOGOFPercent.setSelected(true);
        radBOGOFPercent.setText("percentage off");
        radBOGOFPercent.setEnabled(false);

        buttonGroupBOGOF.add(radBOGOFMoney);
        radBOGOFMoney.setText("money off");
        radBOGOFMoney.setEnabled(false);

        javax.swing.GroupLayout panelMultibuyLayout = new javax.swing.GroupLayout(panelMultibuy);
        panelMultibuy.setLayout(panelMultibuyLayout);
        panelMultibuyLayout.setHorizontalGroup(
            panelMultibuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMultibuyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMultibuy1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMultibuy2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMultibuy3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBOGOFValueOff, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMultibuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radBOGOFMoney)
                    .addComponent(radBOGOFPercent))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMultibuyLayout.setVerticalGroup(
            panelMultibuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMultibuyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMultibuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMultibuy1)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMultibuy2)
                    .addComponent(btnSearchItem)
                    .addComponent(lblMultibuy3)
                    .addComponent(txtBOGOFValueOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radBOGOFPercent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radBOGOFMoney)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        buttonGroupVoucher.add(radMultibuy);
        radMultibuy.setText("Multibuy");
        radMultibuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMultibuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConditionsLayout = new javax.swing.GroupLayout(panelConditions);
        panelConditions.setLayout(panelConditionsLayout);
        panelConditionsLayout.setHorizontalGroup(
            panelConditionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConditionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConditionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelMultibuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelXOffYGetZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConditionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radXOffYGetZ)
                    .addComponent(radMultibuy))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        panelConditionsLayout.setVerticalGroup(
            panelConditionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConditionsLayout.createSequentialGroup()
                .addGroup(panelConditionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConditionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelXOffYGetZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConditionsLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(radXOffYGetZ)))
                .addGroup(panelConditionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConditionsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelMultibuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConditionsLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(radMultibuy)))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Conditions", panelConditions);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radXOffYGetZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radXOffYGetZActionPerformed
        for (Component c : panelXOffYGetZ.getComponents()) {
            c.setEnabled(true);
        }
        panelXOffYGetZ.setEnabled(true);

        for (Component c : panelMultibuy.getComponents()) {
            c.setEnabled(false);
        }
        panelMultibuy.setEnabled(false);
    }//GEN-LAST:event_radXOffYGetZActionPerformed

    private void radMultibuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMultibuyActionPerformed
        for (Component c : panelXOffYGetZ.getComponents()) {
            c.setEnabled(false);
        }
        panelXOffYGetZ.setEnabled(false);

        for (Component c : panelMultibuy.getComponents()) {
            c.setEnabled(true);
        }
        panelMultibuy.setEnabled(true);
    }//GEN-LAST:event_radMultibuyActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        String name = txtName.getText();
        Voucher v = new Voucher(name, Voucher.VoucherType.XOnYGetZOff, "", "", "", "", "", "", "", "");
        try {
            dc.addVoucher(v);
            update();
        } catch (IOException | SQLException ex) {
            showError(ex);
        }
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        btnAddNew.doClick();
    }//GEN-LAST:event_txtNameActionPerformed

    private void tableVouchersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVouchersMouseClicked
        Voucher v = currentTableContents.get(tableVouchers.getSelectedRow());
        setCurrentVoucher(v);
    }//GEN-LAST:event_tableVouchersMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (voucher != null) {
            try {
                if (JOptionPane.showConfirmDialog(this, "Delete " + voucher.getName() + "?") == JOptionPane.YES_OPTION) {
                    dc.removeVoucher(voucher);
                    setCurrentVoucher(null);
                    update();
                }
            } catch (IOException | SQLException | VoucherNotFoundException ex) {
                showError(ex);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearchItem;
    private javax.swing.ButtonGroup buttonGroupBOGOF;
    private javax.swing.ButtonGroup buttonGroupVoucher;
    private javax.swing.ButtonGroup buttonGroupXonYgetZ;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblMultibuy1;
    private javax.swing.JLabel lblMultibuy2;
    private javax.swing.JLabel lblMultibuy3;
    private javax.swing.JLabel lblXYZ1;
    private javax.swing.JLabel lblXYZ2;
    private javax.swing.JLabel lblXYZ3;
    private javax.swing.JPanel panelConditions;
    private javax.swing.JPanel panelMultibuy;
    private javax.swing.JPanel panelVouchers;
    private javax.swing.JPanel panelXOffYGetZ;
    private javax.swing.JRadioButton radBOGOFMoney;
    private javax.swing.JRadioButton radBOGOFPercent;
    private javax.swing.JRadioButton radMoney;
    private javax.swing.JRadioButton radMultibuy;
    private javax.swing.JRadioButton radPercent;
    private javax.swing.JRadioButton radXOffYGetZ;
    private javax.swing.JTable tableVouchers;
    private javax.swing.JTextField txtBOGOFValueOff;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtValue;
    private javax.swing.JTextField txtValueOff;
    // End of variables declaration//GEN-END:variables
}
